apiVersion: v2
name: termix
description: A Helm chart for deploying Termix terminal sharing application
type: application
version: 1.11.4
appVersion: "release-1.11.1"
keywords:
  - termix
  - terminal
  - sharing
maintainers:
  - name: Eric Schnabel
    email: donotspam@me.com
